#!/bin/bash

# Install Python package
pip install -e .
# Install Javascript dependencies
npm install # or yarn
# Build JupyterLab extension
npm run build # or yarn build
# Install JupyterLab extension
jupyter labextension install .